### ISSUE TITLE
Ошибка assert "Лотошино" in driver.title

### ISSUE THREAD

**Issue by alexyvassili** [alexyvassili/autopublisher#42]
Ошибка `assert "Лотошино" in driver.title`:

- Нужно разобраться, почему она возникает
- Нужно сделать так, чтобы эта ошибка не ломала бота
- И вообще нужно генерировать не ассеры, а исключения
- Конкретно в этом месте может быть вообще нужен ретрай

```
Traceback (most recent call last):
  File "/home/alexey/.python3/venvs/autopublisher/lib/python3.11/site-packages/telegram/ext/dispatcher.py", line 340, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/alexey/.python3/venvs/autopublisher/lib/python3.11/site-packages/telegram/ext/conversationhandler.py", line 465, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexey/.python3/venvs/autopublisher/lib/python3.11/site-packages/telegram/ext/handler.py", line 119, in handle_update
    return self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexey/.python3/venvs/autopublisher/lib/python3.11/site-packages/autopublisher/bot/mailbot.py", line 125, in publish_news
    url = publish.news(current_mail.title, html, current_mail.images)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexey/.python3/venvs/autopublisher/lib/python3.11/site-packages/autopublisher/publish/publish.py", line 113, in news
    driver: WebDriver = login_to_site()
                        ^^^^^^^^^^^^^^^
  File "/home/alexey/.python3/venvs/autopublisher/lib/python3.11/site-packages/autopublisher/publish/publish.py", line 57, in login_to_site
    assert "Лотошино" in driver.title
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by alexyvassili** [comment]
v4.0.0 добавлен ретрай
